JoelNiklaus/SwissCourtRulingCorpus

- README.md
- scrc/utils/debug_utils.py
Checking if the detected sections paragraphs are correct is difficult. This PR adds some helpers to visualize the detected sections and paragraphs to quickly visually check the accuracy within the terminal.
- shows sections fully or compacted
- shows paragraphs
- allows to break right after the visualization to inspect the text and the context
Mostly useful for decision based on pdf's, as their text is sometimes poorly extracted and regex missmatches are common.
Visualizing sections:
easily spotted missmatch in split paragraphs:
> Debugging helper for section splitting

- README.md
- scrc/preprocessors/extractors/spider_specific/section_splitting_functions.py
Only misses a single [decision](https://www.bvd-entscheide.apps.be.ch/tribunapublikation/tribunavtplus/ServletDownload/120_2009_12_5ddb385fa6494ba4b07719b4d67e5ac4.pdf?path=2158c5b82986fcdf66411aa2b35a5fbfa9bd4cad399fc778a29bc6db09252a92144ef372f0c19d94924f63dfbb9b065b70de0c98a231c33cff348ef7ffcc9e7fc7e5823c5f56d15b5ccea900c4ed31a27112b23a39ba43d65720f3addd472759&pathIsEncrypted=1&dossiernummer=120_2009_12) which is very pooly formatted.
Accuracy is technically 99.91%, but I can't say much for the quality. Might look into it again when debugging tools are merged or with some info from issue https://github.com/JoelNiklaus/SwissCourtRulingCorpus/issues/20.
As it was the first spider with pdf's as input (i think?) I just came up with what i felt might be suited for this spider without too …
> Section splitting be bvd

- scrc/preprocessors/extractors/spider_specific/judgment_extracting_functions.py
BS_Omni unlike the already implemented extracting function CH_BGer does not use Numbers such as 1. ..... 2. .... to list the different decisions. (Hauptbegehren, Nebenbegehren etc). It is a plain text in which in the first or rarely the first _few_ sentences list the ultimate decision. 
I have adapted the functions to first check whether a ruling adheres to the numbered structure or not. If it adheres to the numbered structure we will use the already implemented function of CH_BGer. If it is unnumbered, we will search over the whole text to find matches. All matches positions will then be compared to extract the first instance. The first instance of a match is almost all the time the main decision (Hauptbegehren). 
This also increases the amount of judgments extracted for CH_BGer since …
> Bs omni judgment extractor

- scrc/preprocessors/abstract_preprocessor.py
- scrc/preprocessors/extractors/section_splitter.py
The coverage report at the end of parsing is not shown for users who have readonly access to the database. This PR ensures logs are written in distinguishable format and a coverage report can be retrieved even without database access.
Furthermore the report can also be retrieved at breakpoints, allowing to check coverage without running the full spider. In that case the report only considers files that have been parsed so far, giving the correct % of detected sections. This process can be repeated at several breakpoints, the coverage will be updated dynamically.
Run any spider as `readonly` user *OR* set a breakpoint in the context `section_splitter:process_one_spider:<any df>` and call `self.log_coverage_from_json(engine, spider, lang, batchinfo)` with the parameters already set in the …
> extend coverage report to readonly users

- scrc/preprocessors/extractors/section_splitter.py
- scrc/preprocessors/extractors/spider_specific/section_splitting_functions.py
Until now an error was raised when the helper could not associate text to all sections. This leads to decision being discarded which only lack a single section. For example a section with missing footer will be discarded, even though the other sections might be perfectly usable for tasks down the line. Now the warning is logged by the logger, but the result is returned anyway, preventing empty results.
There are decisions which concat the facts and considerations into a single section. There are also decision without any footers. As it was not possible to just pass fewer section markers or empty section markers, the functionality has been extended to accept a custom set of sections.
An assertion ensures that the passed section_markers match the passed sections list to prevent errors while …
> Extend section splitting helpers

- scrc/utils/debug_utils.py
- add url to the options, to access the decision pdf/webpage more easily when debugging
- improve layout of printed decision for easier overview
- The url is very commonly used to dissect why a decision was not correctly split
- the layout can be read faster 
No tests so far.
Now line-breaked between sections and link at the bottom (if passed to debug)
> improve debug utils

- CONTRIBUTING.md
- scrc/enums/section.py
- scrc/preprocessors/extractors/section_splitter.py
- scrc/preprocessors/extractors/spider_specific/section_splitting_functions.py
added section splitting for BE_ZivilStraf spider.
The german parser sadly missed a lot of rulings as the section cannot be distinguished by regex alone.
Example: The first match is within a summary in the considerations section, the other is the header of the ruling:
There is no easy way to fix this, and none of the possibilites are really worth the effort I'm afraid.
The spider could still be improved, but for the last ~15% of missed sections nearly all are edge-cases with typos or do not have a clean structure.
- This spider does not have a facts section. Facts and considerations are concatenated. I filled them into the considerations section.
This PR depends on https://github.com/JoelNiklaus/SwissCourtRulingCorpus/pull/26. It will not work otherwise, as it uses the new functionality …
> add section splitting for BE_ZivilStraf

- scrc/data_classes/procedural_participation.py
- scrc/preprocessors/extractors/spider_specific/procedural_participation_extracting_functions.py
I added the helper functions `get_participation_from_header`, `search_lawyers`, `add_representation`, `get_party`, and `get_procedural_participation` to `procedural_participation_extracting_functions.py` so that several different courts can use these functions. I then changed the courts I'm working on so that they use these helper functions. The wording of the procedural participants seems similar enough that several courts can use the same functions.
I changed `data_classes/procedural_participation.py` to use `counsel.gender.value` instead of `counsel.gender` because I got a `TypeError: Object of type Gender is not JSON serializable` otherwise.
> Helper functions for procedural participation extraction

- scrc/preprocessors/extractors/spider_specific/section_splitting_functions.py
I improved the section splitting, mostly by changing the regexes. I added some keywords that I had previously missed and removed some keywords that led to false positives. The coverage is higher in most cases, except for some footers and headers where it is lower due to better accuracy (because I removed false positives).
I also changed the html extraction logic of the ZH_Sozialversicherungsgericht. This court has a lot of different html structures and the new logic captures more possible structures and differentiates better between.
> Improve section splitting

- scrc/preprocessors/extractors/spider_specific/judgment_extracting_functions.py
The idea is to use the start and end position of the match, to then handle the different cases. In the actual code for  _CH_BGer_, overlaping matches are simply removed by two rules. As the regexes in all_judgment_markers can grow, this makes maintaining maybe hard in the future. Rather compare the position of the match and check whether matches overlap or not . E.g.
- _Gutheissung der Beschwerde_  and 
- _Teilweise Gutheissung der Beschwerde_
> Judgment extracting

- scrc/preprocessors/extractors/spider_specific/section_splitting_functions.py
- I added two lines to the section splitting for the ZH_Sozialversicherungsgericht to clean the paragraphs before appending them to the saved paragraphs. 
- I added a step to replace br tags with spaces and insert spaces before div end tags before using get_text().
- To prevent weird characters from appearing in the saved sections.
- To prevent words separated by br or div tags from getting stuck together when using get_text()
> Section splitting fixes

- scrc/preprocessors/extractors/spider_specific/section_splitting_functions.py
Added the section splitting for the following spider: BE_Verwaltungsgericht.
- Header:  6598 / 6598 (100.00%)
- Facts:   6400 / 6598 (97.00%) 
- Considerations:  6482 / 6598 (98.24%) 
- Rulings: 6418 / 6598 (97.27%) 
- Footer:  6596 / 6598 (99.97%) 
Results for FR language: 
- Header:  679 / 679 (100.00%) 
- Facts:   662 / 679 (97.50%)
- Considerations:  661 / 679 (97.35%) 
- Rulings: 679 / 679 (100.00%) 
- Footer:  679 / 679 (100.00%)
Remark: 
- two decisions without footer
> Section splitting for BE_Verwaltungsgericht

- scrc/preprocessors/extractors/spider_specific/section_splitting_functions.py
//Divided the two spiders from PR #41
Added the section splitting for the following spider: BE_Steuerrekurs.
- Header: 107 / 107 (100.00%)
- Facts: 106 / 107 (99.07%)
- Considerations: 107 / 107 (100.00%)
- Rulings: 106 / 107 (99.07%)
- Footer: 107 / 107 (100.00%)
Results for FR language:
- Header: 12 / 12 (100.00%)
- Facts: 11 / 12 (91.67%)
- Considerations: 12 / 12 (100.00%)
- Rulings: 12 / 12 (100.00%)
- Footer: 12 / 12 (100.00%)
> Section splitting for BE_Steuerrekurs

- scrc/preprocessors/extractors/spider_specific/section_splitting_functions.py
Added the section splitting for the following spider: GR_Gerichte.
- Header: 10301 / 10301 (100.00%) 
- Facts:  9542 / 10301 (92.63%) 
- Considerations: 9542 / 10301 (92.63%) 
- Rulings:        8760 / 10301 (85.04%) 
- Footer: 900 / 10301 (8.74%) 
Results for IT language:
- Header: 1006 / 1006 (100.00%) 
- Facts:  847 / 1006 (84.19%) 
- Considerations: 640 / 1006 (63.62%) 
- Rulings:        941 / 1006 (93.54%) 
- Footer: 14 / 1006 (1.39%) 
Remarks:
-nearly all of them do not have a footer
-some decisions are missing "Considerations"
-found decisions that are probably written in Romansh  [example:](https://entscheidsuche.gr.ch/tribunavtplus/ServletDownload/A_2016_29_754e9e8689c344e7876786069ed75ffc.pdf?path=b7575f62f2ae80f012d42c5d583ce4c1c246bfce97cd964659465e2e510 …
> Section splitting for GR_Gerichte

- scrc/data_classes/person.py
- scrc/data_classes/procedural_participation.py
- scrc/enums/title.py
- scrc/preprocessors/extractors/spider_specific/procedural_participation_extracting_functions.py
- scrc/utils/test_utils.py
I added more tests so that I could test a broader range of decisions. This allowed me to find some cases where the procedural extraction didn't work as expected. For example, it didn't work for names with an ampersand or a dash. So I added those and also added some additional letter characters to the regex. This allows to find more names.
But I was wondering if it's correct to include titles (such as Dr.) for natural persons in their names. I've included them in the participation extraction but maybe that needs to be changed.
> More tests & improvements for participation extraction

- scrc/preprocessors/extractors/spider_specific/section_splitting_functions.py
Added the section splitting for the following spider: CH_BSTG.
- Header: 4356 / 4356 (100.00%) 
- Facts:  3390 / 4356 (77.82%) 
- Considerations: 4298 / 4356 (98.67%) 
- Rulings:        4023 / 4356 (92.36%) 
- Footer: 3974 / 4356 (91.23%) 
Results for FR language:
- Header: 2970 / 2970 (100.00%) 
- Facts:  2913 / 2970 (98.08%) 
- Considerations: 2733 / 2970 (92.02%) 
- Rulings:        2661 / 2970 (89.60%) 
- Footer: 2775 / 2970 (93.43%) 
Results for IT language:
- Header: 1144 / 1144 (100.00%) 
- Facts:  1045 / 1144 (91.35%) 
- Considerations: 1004 / 1144 (87.76%) 
- Rulings:        1030 / 1144 (90.03%) 
- Footer: 1080 / 1144 (94.41%) 
Remarks:
- The URLs generated for the PDFs do not work anymore. They did work, a while ago, way before our presentations. Now, …
> Section splitting for CH_BSTG

- scrc/preprocessors/extractors/spider_specific/section_splitting_functions.py
Added the section splitting for the following spider: SO_Omni.
First of all, I think it is important to mention that I am being shown an odd number of decisions: 9k, while they should probably be around 5k. Therefore, I do not know how trustworthy my numbers are.
On top of this, I have the feeling there are decisions that are not on [Entscheidsuche](https://entscheidsuche.ch/). Why do I believe so it is because I searched, for example, for a decision from 15 December 2007 that did show up in my terminal, but it does not exist on the website under Solothurn.
**Results for DE language:**
- Header: 9293 / 9293 (100.00%) 
- Facts:  6923 / 9293 (74.50%) 
- Considerations: 7036 / 9293 (75.71%) 
- Rulings:        5703 / 9293 (61.37%) 
- Footer: 5740 / 9293 (61.77%)
**Remarks:**
There are mainly …
> Section splitting for SO_Omni

- scrc/preprocessors/extractors/section_splitter.py
- scrc/preprocessors/extractors/spider_specific/section_splitting_functions.py
Added the section splitting for the following spider: BL_Gerichte.
- Header: 6392 / 6399 (99.89%) 
- Facts:  6153 / 6399 (96.16%) 
- Considerations: 6219 / 6399 (97.19%) 
- Rulings:        5326 / 6399 (83.23%) 
- Footer: 46 / 6399 (0.72%)
Remarks:
- only a few have footer
- lots of them are lacking the section "Rulings"
- a few of them are missing one section, or sometimes two
- and for this spider, I found many different types of "formats":
1. [Format 1](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/steuergericht/entscheide-des-steuergerichts-2018/entscheide-in-pdf/2018-03-23-stger-1.pdf/@@download/file/2018-03-23-stger-1.pdf)
2. [Format 2](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/zwangsmassnahmengericht/2012/do …
> Section splitting for BL_Gerichte

- scrc/preprocessors/extractors/spider_specific/judgment_extracting_functions.py
There is only 2 different structures within a court:
- numbered ruling structure
- unnumbered ruling structure
Implemented judgment_outcome functions for all unnumbered courts and set default to numbered ruling.
> Simplifies Judgment Extracting Functions

- scrc/analyses/coverage_verification.py
- scrc/enums/section.py
- scrc/preprocessors/abstract_preprocessor.py
- scrc/preprocessors/extractors/judgment_extractor.py
- scrc/preprocessors/extractors/judgment_pattern_extractor.py
- scrc/preprocessors/extractors/pattern_extractor.py
- scrc/preprocessors/extractors/section_splitter.py
- scrc/preprocessors/extractors/spider_specific/judgment_extracting_functions.py
- scrc/preprocessors/extractors/spider_specific/section_splitting_functions.py
- scrc/preprocessors/text_to_database.py
- scrc/utils/sql_select_utils.py
- Implements coverage verification for section_splitting & judgment_outcome
- Fixes section_splitting & judgment_outcome as it was bugged by the introduction of the new topic section
- Now returns empty list if a specific section was not defined in the section_splitting_function. This means that there is no need to define all sections sections anymore if some sections do not exist.
- Needed to add seperate judgment_extraction function for BS_Omni since it is of unnumbered structure. All unnumbered courts need not to run the defaullt (XX_Spider) function.
> Implements coverage verification, fixes Section_splitting & Judgment_outcome
